<?php

declare(strict_types=1);

$targetDir = dirname(__DIR__, 4) . '/config/autoload';

$env = getenv('APP_ENV');
$targetFile = $targetDir . "/authentication.$env.php";

if (file_exists($targetFile)) {
    echo "\033[33m⚠ File 'authentication.$env.php' already exists at config/autoload/. Skipping ...\n\033[0m";
    return;
}
$keyPair = sodium_crypto_sign_keypair();
$publicKey = base64_encode(sodium_crypto_sign_publickey($keyPair));
$privateKey = base64_encode(sodium_crypto_sign_secretkey($keyPair));
$cookieSecretKey = base64_encode(openssl_random_pseudo_bytes(32)); 
$cookieIv = bin2hex(random_bytes(8));

$template = <<<PHP
<?php

declare(strict_types=1);

use Laminas\Authentication\Adapter\DbTable\CallbackCheckAdapter;

return [
    'authentication' => [
        'adapter'         => [
            'type'    => CallbackCheckAdapter::class,
            'class'   => 'Authentication\AuthenticationAdapter',
            'options' => [
                'table'             => 'users',
                'identity_column'   => 'email',
                'credential_column' => 'password',
            ],
        ],
        'form'            => [
            'username' => 'username',
            'password' => 'password',
        ],
        'sensitive_fields' => [
            'password',
        ],
        'jwt_user_fields' => [ // this field will be encoded in the details section in the json web token.
            'id',
            'email',
        ],
        'token'           => [
            // Public and private keys are expected to be Base64 encoded.
            // The last non-empty line is used so that keys can be generated with
            'public_key' => '$publicKey',
            // The secret keys generated by other tools may
            // need to be adjusted to match the input expected by libsodium.
            'private_key' => '$privateKey',
            // If set to true, a session_ttl value will be stored in the cache storage.
            // To ensure the mechanism works correctly, it is recommended to trigger the /api/auth/session route every 5-15 minutes.
            'enable_session_ttl' => false,
            // for strong security reason it should be less
            'session_ttl' => 15, // in seconds (TTL value cannot be less than 10 minutes)
            // you can reduce the time for higher security
            // for how long the token will be valid in the app.
            // in every "x" time the token will be refresh.
            'token_validity' => 60, // in minutes
            // choose your algorithm:  EdDSA, HS256, HS384, HS512
            'algorithm' => 'EdDSA', // recommended
            // grace period in seconds
            'leeway' => 60,
            // Cookie encryption
            'encryption' => [
                'iv'         => '$cookieIv', // generate random 16 chars
                'enabled'    => false, // it should be true in production environment
                'secret_key' => '$cookieSecretKey',
            ],
            // whether to check the IP and User Agent when the token is resolved.
            'validation' => [
                'user_ip'    => false,
                'user_agent' => false,
            ],
        ],
    ],
];

PHP;

file_put_contents($targetFile, $template);
echo "\033[32m✔ Configuration file 'authentication.$env.php' successfully created in config/autoload/\n\033[0m";
